name: Run GSC URL Inspector

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    # Runs 3 times a day at 8:00, 16:00, 00:00 IST (2:30, 10:30, 18:30 UTC)
    - cron: '30 2,10,18 * * *'

jobs:
  inspect-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for google-github-actions/auth

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate using the Service Account Key JSON stored in secrets
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run GSC URL Inspector Action
        uses: yuvraajsj18/gsc-url-inspect-action@v1.0.0
        with:
          # Path to the input YAML in this repository
          input-yaml-path: 'constants/gsc-url-inspect-list.yaml'
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload Inspection Results Artifact
        uses: actions/upload-artifact@v4
        # Ensure this step runs even if the previous one failed but generated a partial report
        if: always()
        with:
          name: inspection-results
          # Path to the file generated by the action
          path: results.yaml
          if-no-files-found: error # Optional: error, warn, or ignore if the file doesn't exist
